- name: set crontab
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
  with_items:
    - { name: 'backwpup', hour: '*', user: 'nobody', job: '/usr/bin/php -q /var/www/html/wp/wp-cron.php >/dev/null 2>&1' }
