- name: install mysql repo
  yum: name="{{ MYSQL_VERSION }}" state=present

- name: install mysql
  yum: name={{ item }} state=present enablerepo=mysql57-community,mysql-tools-community,mysql-connectors-community
  with_items:
    - mysql-server
    - mysql
    - mysql-devel
    - MyQSL-python


- name: service start mysql
  service: name=mysqld state=started enabled=yes

- name: get generate password for mysql
  shell: "grep 'password is generated' /var/log/mysqld.log | awk -F'root@localhost: ' '{print $2}'"
  register: generate_pass

- name: replace .my.cnf
  template:
    src: "roles/mysql/template/.my.cnf"
    dest: "/root/"

- name: get password
  lineinfile:
    path: /root/.my.cnf
    state: present
    regexp: "{{ item.match }}"
    line: "{{ item.line }}"
  with_items:
    - { match: 'password=', line: 'password={{ generate_pass.stdout }}' }

## mysql操作セクション例　（あくまで例です）
# - name: set password for root
#   mysql_user:
#     name: "{{ mysql_login_user }}"
#     host: localhost
#     password: "{{ generate_pass.stdout }}"

# - name: set mysql user
#   mysql_user:
#     name: "{{ db_user }}"
#     password: "{{ db_pass }}"
#     priv: '*.*:GRANT'
#     host: localhost

# - name: remove anonymous user
#   mysql_user:
#     name: ''
#     host: localhost
#     state: absent
#
# - name: remove test DB
#   mysql_db:
#     name: test
#     state: absent
#     host: localhost

